//Users Action Types
export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

//Messages Action Types
export const MESSAGES_REQUEST = "MESSAGES_REQUEST";
export const MESSAGES_ERROR = "MESSAGES_ERROR";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const POST_MESSAGES_SUCCESS = "POST_MESSAGES_SUCCESS";
